### ISSUE TITLE
如果界面还有其他RecycleView, 动画中的弹幕会卡顿

### ISSUE THREAD

**Issue by hike2008** [xujiaji/DMView#1]
如题;
其他RecycleView 进行notifyInsert的时候, 会导致动画中的弹幕卡顿

**Comment by xujiaji** [comment]
你使用的RecyclerView支持包版本号是多少呢？当前我使用的**24.1.1**没有出现你说的问题

**Comment by hike2008** [comment]
24.1.0, 那我再试试

**Comment by xujiaji** [comment]
那么因该不是版本的问题吧

**Comment by xujiaji** [comment]
![ezgif-4048154577](https://cloud.githubusercontent.com/assets/16447251/18264895/6a3e759a-7445-11e6-8e1b-4654109ef71d.gif)
这是我的演示效果与对应的apk，如果有时间你试试看能行不
[测试两个RecyclerView.apk.zip](https://github.com/xujiaji/DMView/files/456136/RecyclerView.apk.zip)
